### ISSUE TITLE
Failed tracing errors on xray.getSamplingTargets and x-ray.getSamplingRules

### ISSUE THREAD

**Issue by fjsousa** [aws/aws-xray-sdk-node#100]
I get failed tracing errors on `xray.getSamplingTargets` and `xray.getSamplingRules` calls after enabling tracing for all Amazon clients: 

```const AWS = AWSXRay.captureAWS(require('aws-sdk'))```

The failed traces are polluting the logs, but otherwise, they're not a big issue. I can't, however, figure out how to avoid them:

> "Call xray.getSamplingRules is missing the sub/segment context for automatic mode. Ignoring."
> "Call xray.getSamplingTargets is missing the sub/segment context for automatic mode. Ignoring."

Seems like X-Ray traces its own calls when capturing the entire AWS SDK. I

n my app, I'm actually interested in capturing DynamoDB calls only. I've tried capturing it like this but I don't seem to get any traces.

```
const dynamo = AWSXRay.captureAWSClient(new AWS.DynamoDB({...})
                                            
db = new AWS.DynamoDB.DocumentClient({
      service: dynamo,
      params: ...})
```

Is it maybe because I'm using `AWS.DynamoDB.DocumentClient`?

**Comment by chrisradek** [comment]
@fjsousa 
We should make sure that we don't attempt to trace calls made by the xray sdk, so I'll mark that as a bug since based on your findings we're doing just that.

The DynamoDB DocumentClient is interesting in that even when you pass in a service client, it is actually creating a new service client based on the configuration of the client you gave it. That means if you try to pass in a 'captured' client, it won't have any affect as a new client is created anyway.

2 ways to work-around this then would be:
1. Call `AWSXRay.captureAWSClient(db.service);` after you instantiate the `DocumentClient`. This will trace calls only made by your DocumentClient.
2. Call `AWSXRay.captureAWSClient(DynamoDB.prototype);`. This will have a wider affect since it will cause any DynamoDB calls to be traced, not just the ones made by your DocumentClient.

**Comment by fjsousa** [comment]
Thanks, @chrisradek. Went with number one and it worked like a charm. Still some dynamo traces are failing with a missing context failure but that's an unrelated issue I think.

**Comment by fjsousa** [comment]
@chrisradek also, globally capturing http calls seems to produce a similar error (plus other failed traces). I've got a service where I'm capturing dynamo db (capturing `DocumentClient` as you described above) and outbound http calls with:

```
AWSXRay.captureHTTPsGlobal(require('http'));
AWSXRay.capturePromise();
var request = require('request-promise');

```
X-Ray tries to trace all outboud http calls (including ones made internally by the AWS client) but some fail with missing context like:

`Options for request [ host: 169.254.169.254, method: GET, path: /latest/meta-data/iam/security-credentials/ ] is missing the sub/segment context for automatic mode. Ignoring.`

`Options for request [ host: 127.0.0.1, method: POST, path: /SamplingTargets ] is missing the sub/segment context for automatic mode. Ignoring.`

**Comment by chrisradek** [comment]
@fjsousa 
Those errors are peculiar. When you get those Options errors, do you also failures creating traces for your AWS calls?

Are you able to provide a small code sample that reproduces this issue? It seems like context is getting lost when your credentials are refreshed, which would be odd if the AWS operation the that triggers the refresh was being traced properly.

**Comment by fjsousa** [comment]
> @fjsousa
> Those errors are peculiar. When you get those Options errors, do you also failures creating traces for your AWS calls?

No, my Dynamo DB calls show up in the X-Ray console. 

> Are you able to provide a small code sample that reproduces this issue? It seems like context is getting lost when your credentials are refreshed, which would be odd if the AWS operation the that triggers the refresh was being traced properly.

Sure, let me try and reproduce the error in a concise code example.
