### ISSUE TITLE
Add support for setUser

### ISSUE THREAD

**Issue by SamVerschueren** [aws/aws-xray-sdk-node#107]
Hi!

I was looking for a way to attach my user id to my trace so I could use the `Group by User` in the XRay console.

I noticed that Java has a `setUser(id)` method which is documented [here](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-segment.html#xray-sdk-java-segment-userid).

I tried to do the same in Node.js but looked into the code and couldn't find anything regarding this.

In AWS Lambda, I ended up doing this:

```
AWSXRay.captureFunc('annotations', subsegment => {
	subsegment.addAnnotation('UserID', ctx.user.id);
});
```

After that, the `Group By` function in the console showed `Annotation.UserID` and I could use the filter and grouping functionality.

![image](https://user-images.githubusercontent.com/1913805/54983887-f8959580-4fad-11e9-9b8d-58f9834514e0.png)

I just think it would be nice if you could just do `AWSXRay.getSegment().setUser(id)` just like in Java without using a custom annotation. That way, we could use the predefined `Group By User` from the console instead of a custom annotation.

![image](https://user-images.githubusercontent.com/1913805/54983947-182cbe00-4fae-11e9-94e8-461be5006125.png)

**Comment by willarmiros** [comment]
v2.5.0 has been released which includes `setUser()`. Unfortunately this function cannot be made available in Lambda since segments made in Lambda are immutable, and `setUser()` can only be applied to segments rather than subsegments.

Public docs for the function will be available [here](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-segment.html) in the next couple hours.
