### ISSUE TITLE
npm package 2.3.3-experimental.1 issues

### ISSUE THREAD

**Issue by keroic** [aws/aws-xray-sdk-node#134]
Found that the Experimental Package was not working and keep throw Failed to get the current sub/segment from the context.

I have tried to install 2.2.0 and 2.3.3 to make comparison.

Seems the cls require was point to continuation-local-storage instead of cls-hooked and cause the case.

Is it possible to release another npm Experimental package release, thanks!

**Comment by yogiraj07** [comment]
Hi @keroic ,
Can you clear your node_modules folder and install experimental SDK via npm : `npm install —save aws-xray-sdk@experimental`. 

There hasn't been any change with respect to cls-hooked storage on `experimental` branch. Please let me know if you still face the issue.

Thanks,
Yogi

**Comment by keroic** [comment]
> Hi @keroic ,
> Can you clear your node_modules folder and install experimental SDK via npm : `npm install —save aws-xray-sdk@experimental`.
> 
> There hasn't been any change with respect to cls-hooked storage on `experimental` branch. Please let me know if you still face the issue and the way you are consuming the xray dependency.
> 
> Thanks,
> Yogi

Yes, I have tried to remove the node_modules and also remove the aws-xray-sdk from the package.json, and re-run npm install —save aws-xray-sdk@experimental

And check the node_modules/aws-xray-sdk-core/lib/context_utils.js still state require "continuation-local-storage" package

I have done this for few times, the same result was encountered, moreover, I have tried also run the install in diff Machine, same result returned.

Regards,
Keith

**Comment by yogiraj07** [comment]
Hi @keroic ,
We are looking into this issue. Please stay tune for the update.

**Comment by haotianw465** [comment]
For now you can manually install `aws-xray-sdk-core@experimental` to force the core module depending on `cls-hooked` to be picked up while we are investigating the root cause.

What we've found so far is that the submodules of `aws-xray-sdk` are resolved to wrong url by `npm install`. Here are the relevant `package.json` entries when using different install commands:

NPM version `6.9.0`

**npm install aws-xray-sdk@experimental**:

`aws-xray-sdk/package.json`:

```js
{
  "_from": "aws-xray-sdk@experimental",
  "_id": "aws-xray-sdk@2.3.3-experimental.2",
   "_resolved": "https://registry.npmjs.org/aws-xray-sdk/-/aws-xray-sdk-2.3.3-experimental.2.tgz"
}
```

`aws-xray-sdk-core/package.json`:

```js
{
  "_from": "aws-xray-sdk-core@^2.3.3-experimental.2",
  "_id": "aws-xray-sdk-core@2.3.3",
  "_resolved": "https://registry.npmjs.org/aws-xray-sdk-core/-/aws-xray-sdk-core-2.3.3.tgz"
}
```
As you can see here the core package with version `2.3.3-experimental.2` was resolved to the stable release latest by npm. But if you install `aws-xray-sdk-core@experimental` again:

**npm install aws-xray-sdk-core@experimental**:

`aws-xray-sdk-core/package.json`:

```js
{
  "_from": "aws-xray-sdk-core@experimental",
  "_id": "aws-xray-sdk-core@2.3.3-experimental.2",
  "_resolved": "https://registry.npmjs.org/aws-xray-sdk-core/-/aws-xray-sdk-core-2.3.3-experimental.2.tgz"
}
```
you can get the correction version.

We will share our new findings once we have more.

**Comment by haotianw465** [comment]
So we found the root cause. For the stable release the `aws-xray-sdk/package.json` has been always look like this:

```js
  "dependencies": {
    "aws-xray-sdk-core": "^2.3.3",
    "aws-xray-sdk-express": "^2.3.3",
    "aws-xray-sdk-mysql": "^2.3.3",
    "aws-xray-sdk-postgres": "^2.3.3"
  }
```

For the experimental release it is critical to keep `^` away since `^` allows npm to get the latest version and by `semver` definition `2.3.3` **is** newer than `2.3.3-experimental.*`. For the previous versions of experimental releases the `aws-xray-sdk/package.json` looked like this (no `^` is used):

```js
  "dependencies": {
    "aws-xray-sdk-core": "2.2.0-experimental.1",
    "aws-xray-sdk-express": "2.2.0-experimental.1",
    "aws-xray-sdk-mysql": "2.2.0-experimental.1",
    "aws-xray-sdk-postgres": "2.2.0-experimental.1"
  }
```

But for 2.3.3 release due to merge conflicts from mainline and incorrect conflict resolving, now the head of experimental `aws-xray-sdk/package.json` looks like this (`^` is accidentally added):

```js
  "dependencies": {
    "aws-xray-sdk-core": "^2.3.3-experimental.2",
    "aws-xray-sdk-express": "^2.3.3-experimental.2",
    "aws-xray-sdk-mysql": "^2.3.3-experimental.2",
    "aws-xray-sdk-postgres": "^2.3.3-experimental.2"
  }
```

This results in the stable version `core` picked up by npm. We will release the new patch as soon as possible. In the future we will add unit test to make sure if the wrong dependency is picked up, the test would fail. Sorry for the inconvenience and thank you for your patience.

**Comment by yogiraj07** [comment]
Hi @keroic ,
We have released version `2.3.3-experimental.3`. Would you mind checking if it resolves your issue?

**Comment by keroic** [comment]
Thanks for finding.

I just try to install 2.3.3-experimental.2, but found that already 2.3.3-experimental.3 now, what's quick update!

But, I try to install 2.3.3-experimental.3, seems my web services code would freeze in somewhere, looks like something in "Promise" can't be resolved.

However, when I revert to 2.2.0-experimental.1, my web services code can back to normal.

**Comment by yogiraj07** [comment]
@keroic ,
Can you tell a bit more of the issue with your app.
1. What is the error stack with Promise?
2. How does the call looks like?
3. What is your environment set up? How are you deploying the app?
4. A small reproduction code snippet will be helpful.

**Comment by manchuck** [comment]
This looks like the same problem I'm having in #110 I am running the same version and having issues when running tests
