### ISSUE TITLE
AWS Lambda with Single Subsegment Not Sent

### ISSUE THREAD

**Issue by timtrinidad** [aws/aws-xray-sdk-node#148]
Lambdas automatically come with a root segment that can be captured with

```js
const segment = new AWSXRay.Segment('Root Segment);
AWSXRay.utils.LambdaUtils.populateTraceData(segment, process.env._X_AMZN_TRACE_ID);
```

If you add a single subsegment to that root subsegment (and any number of sub-subsegments to that subsegment), nothing gets sent to Xray.

For example:
* Root Segment (automatically created)
  * subseg Subsegment
    * sleep Subsegment
    * sleep Subsegment
    * sleep Subsegment

I think this is due to [the code in `Subsegment.close()`](https://github.com/aws/aws-xray-sdk-node/blame/master/packages/core/lib/segments/attributes/subsegment.js#L273-L279):

```js
  if (this.parent)
    this.parent.decrementCounter();

  if (root && root.counter > SegmentUtils.getStreamingThreshold()) {
    if (this.streamSubsegments() && this.parent)
      this.parent.removeSubsegment(this);
  }
```
Note that in lambda, [the streaming threshold is set to 0](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/env/aws_lambda.js#L37).

At the moment that all three `sleep` subsegments are closed, the root has a counter of 1. When `subseg.close()` is called, the parent/root's counter gets decremented to 0, and therefore `this.streamSubsegments()` is never called for this subsegment.

This is only a problem on lambda since [`Segment.close()` does nothing](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/env/aws_lambda.js#L47-L56). On non-lambda environments, the last subsegment [is sent along with the root segment during `flush()`](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/segments/segment.js#L338).

Here is my sample application:

```js
AWSXRay.enableManualMode();

const sleep = (parentSegment) => {
  return new Promise(resolve => {
    const subsegment = parentSegment.addNewSubsegment('sleep');
    setTimeout(() => {
      subsegment.close();
      resolve();
    }, 200);
  })
}

module.exports.withSubsegment = async (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = true;

  const segment = new AWSXRay.Segment('multi-no-async');
  AWSXRay.utils.LambdaUtils.populateTraceData(segment, process.env._X_AMZN_TRACE_ID);

  const subsegment = segment.addNewSubsegment('subseg');

  await sleep(subsegment);
  await sleep(subsegment);
  await sleep(subsegment);

  subsegment.close();

  segment.close();

  callback(null, 'done')
};

```

I'm not sure what the right fix is here. Do we modify `aws_lambda.js Segment.close()` to add a call to `flush()`, or do we reorder the operations in `subsegment.close()` to decrement the parent counter only after the call to `streamSubsegments()`?

**Comment by awssandra** [comment]
Hi timtrinidad,

Sorry for the issues, let me help clear up some confusion.

> Lambdas automatically come with a root segment that can be captured with
> const segment = new AWSXRay.Segment('Root Segment);
> AWSXRay.utils.LambdaUtils.populateTraceData(segment, process.env._X_AMZN_TRACE_ID);

While this is technically true, the SDK is configured to automatically create a facade segment when the it [detects it's running in Lambda](https://github.com/aws/aws-xray-sdk-node/blob/5bb00a4107510cd2a830706e5c470daf003aca5a/packages/core/lib/aws-xray.js#L361). The Lambda segment as seen on the X-Ray console is created in the Lambda's runtime start-up code, and is sent asynchronously and independent from the X-Ray SDK. Thus, the facade segment is a placeholder, which only contains the trace it/parent id/sampling decision that Lambda created. It is never meant to be sent. In this way, the X-Ray backend recompiles the full segment via the subsegments sent from the customer code together with the segment sent independently by Lambda. This facade is set on the CLS context, hence why [manual mode is disabled on Lambda](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/env/aws_lambda.js#L23).

By creating the segment manually in this fashion, you are introducing a conflict. The facade segment created with populateTraceData sets the [parent ID to be the ID of the segment](https://github.com/aws/aws-xray-sdk-node/blob/5bb00a4107510cd2a830706e5c470daf003aca5a/packages/core/lib/utils.js#L140), because it's supposed to be a fake copy of the Lambda segment, and never actually be sent.

The Lambda segment sent asynchronously, and the newly created segment decorated with populateTraceData() share the same ID and thus the manually created segment is being rejected by the X-Ray backend due to this ID conflict.

> This is only a problem on lambda since Segment.close() does nothing.

This is only true for the [instance of the facade segment](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/env/aws_lambda.js#L45), not all manually created segments.

If you manually create a new segment with a new ID (but sharing the trace ID and the sampling decision), you'll be able to send a new segment.

So, you have two options, simply create subsegments which will create a single AWS::Lambda::Function node on the X-Ray service map:

```
const segment = new AWSXRay.getSegment();     //returns the facade segment automatically created
const segment.addNewSubsegment('subseg');
```

Or, there's a workaround - create a new segment with a new ID, but this will display your segment as a separate node in the service map (AWS::Lambda::Function -> multi-no-async).

```
const traceData = AWSXRay.utils.LambdaUtils.processTraceData(process.env._X_AMZN_TRACE_ID);
const segment = new AWSXRay.Segment('multi-no-async', traceData.Root, traceData.Parent);
AWSXRay.middleware.resolveSampling(traceData, segment);
```

Hope this helps,
Sandra

**Comment by timtrinidad** [comment]
Sandra,

Thanks for the info! Unfortunately, we're using async/await/promises we we're on manual mode and therefore `getSegment()` won't work. With the second method, we noticed that the separate document sometimes ends up above the `AWS::Lambda::Function`, making the trace in the console more difficult to parse. 

> The Lambda segment sent asynchronously, and the newly created segment decorated with populateTraceData() share the same ID and thus the manually created segment is being rejected by the X-Ray backend due to this ID conflict.

Is this actually the case? When I enable debugging logs, I see that the Segment is sent successfully, since as far as I know you can send a segment multiple times to update things like `in progress` or `end time`.

**Comment by awssandra** [comment]
Hi timtrinidad,

Promises are supported via the X-Ray SDK out of box, and async/await structures are supported via the experimental branch.

As mentioned before, [manual mode is disabled on Lambda](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/env/aws_lambda.js#L23) so I am curious as to how you are using the constructs to achieve that effect. The segment resolution logic for any capture* function (AWS, HTTP/S and other patchers) relies on the CLS context being present.

Keep in mind, you can use the SDK in automatic mode but use manually created segments and subsegments - there is no conflict there. You should be able to use getSegment to grab the initial Lambda segment, and manually create subsegments and manually pass them around, if you are not using the capture* functions.

The segment is sent successfully, but is being rejected by the X-Ray backend, as it is asynchronously sent via the X-Ray Daemon present on the Lambda instance. If a Segment is incorrectly formatted, or has a conflict, this will not appear on the Lambda console. When a segment is sent, it is sent via UDP packet to be picked up by the Daemon. This message is that the packet sent successfully, useful for diagnosing when a segment or subsegment is dangling or failed to close.

**Comment by timtrinidad** [comment]
As per your recommendation, we gave the experimental branch with automatic mode a try, and it works well. Thank you!
