### ISSUE TITLE
Why segment close function is not having any callback or promise or event.

### ISSUE THREAD

**Issue by chaitanya11** [aws/aws-xray-sdk-node#160]
How to identify whether segment got closed successfully (including send UDP data to X Ray Daemon) ? 
Lambda Function will be terminated after returning response, so if we are closing one segment before sending response, UDP data is not getting sent to X Ray Daemon.
Does any one have any inputs on this problem?

**Comment by awssandra** [comment]
Hi chaitnya11,

You can enable debug mode in your Lambda by using environment variables. That will show you when the segment/subsegments are successfully sent.

https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/README.md#environment-variables

Hope this helps!
Sandra

**Comment by chaitanya11** [comment]
Hi @awssandra ,
thanks for taking time and replying.
i was able to see logs of xray sdk where segment/subsegment is sent.
Problem i am facing is lambda will stop executing after response is sent out, we have segment/subsegment close as async function which may not complete it's execution.
I check code in sdk, i didn't find any callback or promise for close function.

**Comment by awssandra** [comment]
Hi chaitanya11,

Would you mind posting a code snippet to reproduce the issue? I cannot quite visualize the flow from the description.

**Comment by chaitanya11** [comment]
Hi @awssandra ,

I am attaching typescript version of code bellow


```
const xray = require('aws-xray-sdk-core-callback-wrapper');

export const TraceApi = (_target: any, _propertyKey: string, descriptor: TypedPropertyDescriptor<any>) => {
    const method = descriptor.value;
    descriptor.value = async function () {
        const rootSegment = new xray.Segment('rootSegment');
        rootSegment.addAnnotation('function', _propertyKey);
        const result = await method.apply(this, arguments);
        rootSegment.close(); // how would we identify whether segment is closed and udp traffic is sent
                            // before returning in next line.
        return result;
    };
};

class sampletest {
    @TraceApi
    static abc(): Promise<any> {
        return new Promise((resolve, reject) => {
            resolve(); // Lambda will stop after resolving response.
        });
    }
}

export const abcd = sampletest.abc;
```


Here is the compiled js code from the above typescript code.

```
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
const xray = require('aws-xray-sdk-core-callback-wrapper');
export const TraceApi = (_target, _propertyKey, descriptor) => {
    const method = descriptor.value;
    descriptor.value = async function () {
        const rootSegment = new xray.Segment('rootSegment');
        rootSegment.addAnnotation('function', _propertyKey);
        const result = await method.apply(this, arguments);
        rootSegment.close(); // how would we identify whether segment is closed and udp traffic is sent
        // before returning in next line.
        return result;
    };
};
class sampletest {
    static abc() {
        return new Promise((resolve, reject) => {
            resolve(); // Lambda will stop after resolving response.
        });
    }
}
__decorate([
    TraceApi,
    __metadata("design:type", Function),
    __metadata("design:paramtypes", []),
    __metadata("design:returntype", Promise)
], sampletest, "abc", null);
export const abcd = sampletest.abc;
```

when executing rootsegment.close() how would we identify whether segment data is sent to xray or not?

**Comment by chanchiem** [comment]
Hey,

We are working internally to get this tested and to find the root cause. Thank you very much for the code snippet. We'll ask for further information if we need it. Please stay tuned.

Thanks

**Comment by chanchiem** [comment]
Hi,

I have made a slight modification to your code so that it prints logs and shows the order in which the methods are executed. This is the resulting code I added (I added a few logging statements and added the call to `abcd`):
```typescript
const xray = require('aws-xray-sdk-core');

const TraceApi = (_target: any, _propertyKey: string, descriptor: TypedPropertyDescriptor<any>) => {
    console.log("in TraceAPI");
    const method = descriptor.value;
    descriptor.value = async function () {
        console.log("in Async func");
        const rootSegment = new xray.Segment('rootSegment');
        rootSegment.addAnnotation('function', _propertyKey);
        console.log("before await");
        const result = await method.apply(this, arguments);
        console.log("after await");
        rootSegment.close(); // how would we identify whether segment is closed and udp traffic is sent
                            // before returning in next line.
        console.log("Segment closed");
        return result;
    };
};
module.exports = TraceApi

class sampletest {
    @TraceApi
    static abc(): Promise<any> {
        console.log("In abc");
        return new Promise((resolve, reject) => {
            console.log("Calling resolve");
            resolve(); // Lambda will stop after resolving response.
            console.log("Resolve done being called.");
        });
    }
}

const k = function() {
    console.log("Test");
}

const abcd = sampletest.abc;
module.exports = abcd;
const z = abcd();
console.log("EOF");
```

The resulting log I get is:
```
in TraceAPI
in Async func
before await
In abc
Calling resolve
Resolve done being called.
EOF
after await
Segment closed
```

Just so that I understand the issue a little more, is the expectation here to add an async `segment.close()` method that returns either a promise, event, or executes a callback, so that its execution can be suspended as a result of the `rootSegment.close()` call? I don't quite understand how this will help ensure that `rootSegment.close()` is called before EOF since execution is suspended as soon as we hit the first `await` operator. Can you elaborate on this a little bit more?

What it sounds like you are looking for is a way to block the asynchronous function call in the `TraceAPI` decorator so that `rootSegment.close()` is sequential and occurs directly after the `abc` method call, rather than finishing past the EOF.

Please let me know if I understand your question correctly. 

What is your overall use case with using Async/await tasks here? I think if I can understand this more, I can provide more information.

Thanks,
Chan Chiem Jeffery Saeteurn

**Comment by chaitanya11** [comment]
With the problem i am facing i created a small serverless project. i am adding that zip here. Please have a look at it @chanchiem 
[code.zip](https://github.com/aws/aws-xray-sdk-node/files/3590577/code.zip)

**Comment by chanchiem** [comment]
I have tested your example code and it still has the same results as mentioned in the previous post. It looks like the issue is related to the fact that the Async method gets finished executing after the interpreter has reached EOF.

The suggestion that I have is to have a blocking mechanism in your application code so that the call to `rootSegment.close()` is deterministic. The problem with using the current implementation in Lambda is that the execution of `rootSegment.close()` may happen after the Lambda function has finished serving the invocation, which is why you are facing this problem. Adding a promise or event to the `segment.close()` method may not be the solution to the issue you are facing.

**Comment by chaitanya11** [comment]
@chanchiem i am adding lambda logs for the above attached code bellow

```
START RequestId: 100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa Version: $LATEST
2019-09-19T06:06:30.952Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	Lambda root segment {"trace_id":"1-5d831ae5-2c9830a98a805ac0215629a0","id":"3dcd3b613b9eabd5","start_time":1568873190.878,"name":"facade","in_progress":false,"counter":1,"service":{"runtime":"node","runtime_version":"v10.16.3","version":"unknown","name":"unknown"},"aws":{"xray":{"sdk":"X-Ray for Node.js","sdk_version":"unknown","package":"unknown"}},"notTraced":true,"facade":true}
2019-09-19T06:06:30.952Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	Setting lambda root segment {"trace_id":"1-5d831ae5-2c9830a98a805ac0215629a0","id":"3dcd3b613b9eabd5","start_time":1568873190.878,"name":"facade","in_progress":false,"counter":1,"service":{"runtime":"node","runtime_version":"v10.16.3","version":"unknown","name":"unknown"},"aws":{"xray":{"sdk":"X-Ray for Node.js","sdk_version":"unknown","package":"unknown"}},"notTraced":true,"facade":true}
2019-09-19T06:06:30.952Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	Root segment after adding lambda root segment {"trace_id":"1-5d831ae5-2c9830a98a805ac0215629a0","id":"f4d75f4eaa7c8ac4","start_time":1568873190.879,"name":"samele_root-segment","in_progress":true,"counter":0,"service":{"runtime":"node","runtime_version":"v10.16.3","version":"unknown","name":"unknown"},"aws":{"xray":{"sdk":"X-Ray for Node.js","sdk_version":"unknown","package":"unknown"}},"parentId":"3dcd3b613b9eabd5"}
2019-09-19T06:06:30.952Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	In abc
2019-09-19T06:06:30.952Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	Calling resolve
2019-09-19T06:06:33.956Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	abc done now
2019-09-19T06:06:33.957Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	Resolve done being called.
2019-09-19T06:06:33.957Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	Closing root segment {"trace_id":"1-5d831ae5-2c9830a98a805ac0215629a0","id":"f4d75f4eaa7c8ac4","start_time":1568873190.879,"name":"samele_root-segment","in_progress":true,"counter":0,"service":{"runtime":"node","runtime_version":"v10.16.3","version":"unknown","name":"unknown"},"aws":{"xray":{"sdk":"X-Ray for Node.js","sdk_version":"unknown","package":"unknown"}},"parentId":"3dcd3b613b9eabd5"}
2019-09-19T06:06:33.974Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	Successfully Closed root segment
2019-09-19T06:06:33.974Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	is root segment closed true
2019-09-19T06:06:33.974Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	INFO	Resolving api response ...
2019-09-19T06:06:34.032Z	100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	ERROR	(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
END RequestId: 100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa
REPORT RequestId: 100e21ee-9c17-4d7a-81e0-f3eecbe4dbaa	Duration: 3196.23 ms	Billed Duration: 3200 ms	Memory Size: 128 MB	Max Memory Used: 77 MB	Init Duration: 871.45 ms	
XRAY TraceId: 1-5d831ae5-2c9830a98a805ac0215629a0	SegmentId: 3dcd3b613b9eabd5	Sampled: false

```

Close segment is called before resolving response, i was able to verify is by ```rootXRaySegment.isClosed()``` method from sdk. So ```rootXRaySegment.close()``` is not happening after the Lambda function has finished serving the invocation.

**Comment by willarmiros** [comment]
Hi @chaitanya11,
If `rootXRaySegment` is being closed before the termination of your Lambda and when you call the function to close it, then what is the lingering issue? It appears your original question of whether a segment is closed or not before Lambda's termination has been answered.

**Comment by chaitanya11** [comment]
@willarmiros after segment is closed, segment data will be sent to XRay daemon as UDP traffic. If that happens, it will appear in logs. But in this case Lambda is getting terminated before sending UDP traffic. That's what the problem here. If you have time please check the code snippet i have attached and get back.

**Comment by willarmiros** [comment]
I did notice in your code package that you have several functions to create and close the root segment of your lambda function. Those operations are not supported because Lambda generates and closes its own *immutable* segment automatically if X-Ray active tracing is enabled. Only subsegments are allowed to be created, modified, and closed by the handler code. See [these docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html) for more on X-Ray with Lambda. Check to see that you are only creating, modifying, and closing only subsegments in your code.

In the logs you attached it did not appear you had the environment variable `AWS_XRAY_DEBUG_MODE` enabled, which would allow you to see whether the UDP message was sent. If you'd like to enable debug mode and attach those logs that may provide some more insights. Also, if you check the [AWS X-Ray Console](https://console.aws.amazon.com/xray/home#) you should be able to see the segment representing this Lambda function as well as any subsegments you generated inside of it.

**Comment by chaitanya11** [comment]
Thanks for the response @willarmiros , code is working fine after moving to subsegments to immutable segment from lambda. 
Closing this issue.
