### ISSUE TITLE
Logging issue

### ISSUE THREAD

**Issue by grahamhar** [aws/aws-xray-sdk-node#163]
I've followed the discussion in https://github.com/aws/aws-xray-sdk-node/issues/2 and tried to set my own logger at a level of error to stop receiving the following logs without any success.

`
AWS_XRAY_DAEMON_ADDRESS is set. Configured daemon address to 169.254.79.2:2000.
AWS_XRAY_CONTEXT_MISSING is set. Configured context missing strategy to LOG_ERROR.
Subsegment streaming threshold set to: 0
`

We setup the X-Ray as below
`
const AWSSDK = require('aws-sdk');
const AWSXRay = require('aws-xray-sdk-core');
AWSXRay.setLogger(loggerForXRAY);
AWSXRay.captureAWS(AWSSDK)
`

Is this something I've approached in the wrong way or is there some other issue?

**Comment by awssandra** [comment]
Hi grahamhar,

So the issue here is that the SDK initializes before loading the custom logger defined, thus the initialization INFO level logs are not routed to the custom logger (and thus are not filtered by log level). We'll need to configure some suppression mechanism (like a suppress logs env variable) or option to configure the logger when initializing.

**Comment by grahamhar** [comment]
Hi @awssandra,

I’m happy to do a PR for this so you have any thoughts on the name for the variable?

**Comment by grahamhar** [comment]
Also would it be viable to start the built in logger at ERROR rather using the default of INFO?

https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/logger.js#L17

**Comment by grahamhar** [comment]
@awssandra I've raised #172 in an attempt to provide a work around to these log messages without changing current functionality.
