### ISSUE TITLE
Subsegments with the wrong parent id

### ISSUE THREAD

**Issue by gdw2** [aws/aws-xray-sdk-node#189]
Using: 2.3.6-experimental.1

I'm running an async-heavy lambda.  Frequently subsegments are assigned to the wrong parent.  The screenshot below shows an example.  I will continue investigating.  I understand that it would be ideal if I could provide a reproducible example.  That might be tricky.  If there's any other useful information I can provide, let me know.  

I understand that this is kind of sparse on specific details, so I'll understand if you have to close it in a few days.

![Xnip2019-09-20_10-37-52](https://user-images.githubusercontent.com/665024/65346944-ccd91e00-db92-11e9-95c7-d6df0386f802.jpg)

**Comment by willarmiros** [comment]
Hi @gdw2,
`async` functions in Lambda has caused some bugs in the past with X-Ray. Although your specific use case is unknown, one thing that can happen is Lambda can drop subsegments if execution reaches the end of the handler and there are still functions in process, Lambda will allow them to resolve but terminate immediately after, interfering with or dropping subsegments that were still open at the time.

The best way to guarantee correctness of subsegments is to use `await` to pause until the completion of a `Promise` that is being traced by X-Ray. This ensures these requests will be completed and their subsegments closed before the Lambda terminates and causes inconsistent behavior.

If you would like further specific assistance, could you provide the (redacted as necessary) JSON from the "raw data" tab? And where do you expect these annotation-segments to be instead of where they are now?

**Comment by willarmiros** [comment]
I'm going to close this, but feel free to follow up if you still have questions.
