### ISSUE TITLE
Documentation for captureAWS caveat is confusing.

### ISSUE THREAD

**Issue by thomasmichaelwallace** [aws/aws-xray-sdk-node#20]
I'm on the cusp of using aws-xray but I have read this caveat for `var AWS = captureAWS(require('aws-sdk'));` about 10 times, and I’m just not getting it:

> Create new clients as usual. Be sure any outgoing calls that are dependent on another async function are wrapped, or duplicate segments might leak.

* If I’m in a lambda function handler and all I do is call into AWS APIs, awaiting the `.promise()` version, do I have to do anything else but wrap the module in `captureAWS`?
* Am I right in understanding _client_ to mean something created using `new AWS.s3()` etc? 
* Isn’t anything I do with a client an outgoing call (e.g. `s3.getObject()`)? Or does “outgoing calls” in this context mean asynchronous actions not using said _clients_ (e.g. `rp.post()`).
* By ‘dependent on’, does it mean that anything in `.then()` (or a babel transpiled await)?

For the sake of people like me, can someone please explain this to me like I'm five (perhaps with an example of when you do, and don't, need to start wrapping things in captureAsyncFunc?).

Assuming I get it, I'm happy to digest it all back into a PR for the documentation to save some confusion for the next person like me!

**Comment by haotianw465** [comment]
Thank you for your feedback and sorry for the confusion. The doc was written before native Promise came out and the SDK doesn't officially support native Promise due to how [CLS](https://github.com/othiym23/node-continuation-local-storage) works. This native promise issue was already addressed here #11 . We will prepare a release soon and add Promise related content to our docs.

For non-Promise related usage you could check this sample app https://github.com/awslabs/aws-xray-rekognition-lambda-sample which uses two Lambda functions and each of them calls some AWS services. Feel free to follow up any question regarding the sample Lambda functions.

You are very welcome to submit a PR on improving the documentation.

**Comment by thomasmichaelwallace** [comment]
OK- so for now using the aws-sdk `.promise()` functions the returned AWSRequest objects don't work? e.g. `s3.getObject().promise()`?

Thanks for the example- I had seen that, but it doesn't really indicate why it's ok to use the asynchronous `cognitoidentity.getCredentialsForIdentity` outside of `captureAsyncFunc` but nothing else?

**Comment by haotianw465** [comment]
I will do some testing around using `.promise()` for AWS call capture and update `README` for what is supported and what is not on latest node version.

For `captureAsync` it is about what you want to capture. Take the sample app as an example, it wants to know how much time it takes to get the credential back. And it is only `cognitoidentity.getCredentialsForIdentity` that matters. In that case `var AWS = captureAWS(require('aws-sdk'));` is enough, the call will be recorded as a subsegment properly.

But for capture a function that iterates all images and recognize persons in those images, it uses `captureAsyncFunc` to wrap the entire business logic, reason being inside the logic there are async calls (in this case it is calls to AWS S3 and AWS Rekognition). This entire function will be captured as a subsegment. All AWS API calls are recorded as subsegments and become direct children of that subsegment representing entire wrapped function.

This could be useful when you see the entire function is taking long but all outbound AWS calls are fast, then it exposes some hidden local issues which otherwise would be really hard to find.

I hope this helps. We will improve our documentation and sample applications to better showcase the instrumentation part. PRs on our documentation are also very welcome.

**Comment by thomasmichaelwallace** [comment]
Thanks @haotianw465.

I did some of my own experiments today and discovered the following.

For a babel transpiled lambda function (6.10), which I guess would be a common use case for asynchronous x-ray usage:
* . promise() from the aws-sdk works out of the box
* so does await/async
* Concurrent aws-sdk .promise() calls work out of the box (e.g. Promise.all())
* You only need to wrap functionality with captureAsyncFunction() when using logical groupings with segments.

I'll try to come up with a documentation PR that clarifies my point of contention: there's nothing specific about the aws-sdk that would require being wrapped by captureAsyncFunction.

**Comment by haotianw465** [comment]
Thank you so much for the information and we really appreciate it. Yes you are absolutely correct that capturing aws-sdk itself doesn't need to be wrapped by `captureAsyncFunc`. The PR from your side of view will add great value to the SDK. 

I have one question. When you say `aws-sdk` calls work do you mean the subsegments representing those calls have correct hierarchy and timing information or you just mean there is no error thrown?

We will do furthermore investigation from our side but it will be very helpful to know what you observed.

**Comment by thomasmichaelwallace** [comment]
No worries @haotianw465 - by work I mean that x-ray seemingly captures all the subsegments and calls with the correct hierarchy and timing information (including when you do a `[aws-sdk].promise().then()` and cross-invoking into another lambda function).

**Comment by thomasmichaelwallace** [comment]
My fix is now merged (for about two years!) so I'm closing this issue.
