### ISSUE TITLE
.setDaemonAddress doesn't configure service_connector.js

### ISSUE THREAD

**Issue by dt-atkinson** [aws/aws-xray-sdk-node#233]
service_connector.js is included on import and uses daemon_config.js on creation.

The configuration isn't reloaded after supplying parameters to setDaemonAddress so will always hit localhost (unless using ENV vars)

**Comment by willarmiros** [comment]
Hi @dt-atkinson,
You're right on this, it looks like the X-Ray client in `service_connector` should be regenerated as part of the `setDaemonAddress` method. I do not believe a new [client ID](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/middleware/sampling/service_connector.js#L19) would have to be generated since the X-Ray client would still be associated with the same service. So it should be a pretty easy fix.

I would welcome a PR to resolve this bug if you're interested.

**Comment by willarmiros** [comment]
This issue is resolved in 3.0.0-alpha.2.
