### ISSUE TITLE
AWS_XRAY_LOG_LEVEL=silent should silent context missing error

### ISSUE THREAD

**Issue by j0k3r** [aws/aws-xray-sdk-node#282]
I was expected that `silent` value to shut down the context missing error too as per defined in the [README](https://github.com/aws/aws-xray-sdk-node/blob/a51b38f50bac262568ecbd2eb1cf7bc805b5bab3/packages/core/README.md#logging-configuration).

Or maybe, when defining `AWS_XRAY_LOG_LEVEL=silent`, `AWS_XRAY_CONTEXT_MISSING` should be defined to `LOG_ERROR`?
Is it something you can think about or you don't want that kind of mixed behavior to happen?

**Comment by willarmiros** [comment]
I personally feel that having the log level setting influence the context missing strategy would be more unexpected than the current behavior, especially since all other log levels would not influence the context missing strategy. However I can understand this use case and if many other customers would prefer it I'd consider a PR.

**Comment by Mangosteen-Yang** [comment]
There are some cases I need to make a request from express to other APIs, in this case, the request is not initialled from a user so no current segment(captureHTTPsGlobal enabled). I will get `Error: Failed to get the current sub/segment from the context` and I can do nothing with it.

If the request not initialled from a user can be captured will be ideal otherwise, I do not need the error.

**Comment by willarmiros** [comment]
@Mangosteen-Yang I mentioned this in #239, but I believe that use case can be handled by only just setting the context missing strategy. Furthermore, after discussion with our team we do not plan on introducing this behavior to keep configurations separate, so I'll be closing this now.

**Comment by Mangosteen-Yang** [comment]
yeah, make sense to me. Thanks.
