### ISSUE TITLE
captureHTTPsGlobal causes exception when using the AppConfig module from aws-sdk

### ISSUE THREAD

**Issue by clementallen** [aws/aws-xray-sdk-node#314]
When using `AWSXRay.captureHTTPsGlobal(require('https')` in conjunction with retrieving config from AppConfig using the `aws-sdk` I get the following error:

```
Error [NetworkingError]: Failed to get the current sub/segment from the context.
```

Here is a minimal repo which can reproduce the issue: https://github.com/clementallen/xray-appconfig

**Comment by srprash** [comment]
Hi @clementallen 
Thanks for providing the repro code. This seems to be a problem because all AWS SDK calls are basically HTTP calls underneath. Since you're application doesn't patch AWS requests using `captureAWS` method but [patches HTTP requests](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/patchers/http_p.js#L82-#L85) using `captureHTTPsGlobal`, the appconfig requests are being recorded as HTTP in a subsegment. Since there's no segment/subsegment present to add this subsegment to, it results in the context missing error.
There are a few workarounds that you can follow here:
1. Open a segment at the start of your application before getting configuration from appconfig and close it in the end. This will let the sdk attach subsegments to this segment and will not throw the error.
2. If you want to suppress the error, you can configure the `AWS_XRAY_CONTEXT_MISSING` environment  variable to `LOG_ERROR` (by default its set to `RUNTIME_ERROR`) or set it [programatically](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#context-missing-strategy-configuration)

**Comment by willarmiros** [comment]
Closing this out, feel free to comment if you need to reopen!
