### ISSUE TITLE
SES and SNS yield TypeError: Cannot read property 'customizeRequests' of undefined

### ISSUE THREAD

**Issue by joshrussell** [aws/aws-xray-sdk-node#343]
When attempting to capture SES or SNS via XRay, I receive the following error: TypeError: Cannot read property 'customizeRequests' of undefined. I received a similar error for DocumentClient but was able to work around that. No such workaround seems to exist for SES or SNS.

aws-sdk version: 2.771.0
aws-xray-sdk version: 3.2.0

I've managed to instrument most of the rest of my application but can't seem to instrument these two clients. Is this known or a workaround?

Example of how I'm attempting to capture the client:

```
this.sesLib = xray.captureAWSClient(new SES(buildConfig()));
```

**Comment by willarmiros** [comment]
Hi @joshrussell,

That's interesting, we are calling `customizeRequests` [here](https://github.com/aws/aws-xray-sdk-node/blob/fdbbdf7b7e788a70d23d25637296b254a6171a2f/packages/core/lib/patchers/aws_p.js#L55). `customizeRequests` is a private API (defined [here](https://github.com/aws/aws-sdk-js/blob/4fd99d087f245f23b164219fba62156af060770e/lib/service.js#L158)) that we take advantage of, and it should be defined on *all* AWS clients because it's an API for the abstract `Service` base class.

Based on your error, it sounds like `new SES(buildConfig())` returns undefined, which is why `customizeRequests` fails. Can you verify this is the case? Or, can you post a larger snippet including the definition of `buildConfig()` so I can try to reproduce this on my end?

**Comment by joshrussell** [comment]
@willarmiros based on your feedback I did some more digging. The failure was happening during unit tests, so the change was never released to a deployed environment. After further digging, the unit test was mocking the entire SNS service from AWS but only with a publish stub, so the customizeRequests method wasn't on the stub. Based on that finding, I'll update the tests and push this to a deployed environment during the next push to see if it runs in a deployed environment.

Given this, I'll close this issue. Thanks for the additional information.
