### ISSUE TITLE
Is it possible to get end to end traces for aws serverless lambda, for all possible triggers otherthan AWS Gateway? 

### ISSUE THREAD

**Issue by bala1074** [aws/aws-xray-sdk-node#346]
Is it possible to get end to end traces for aws serverless lambda, for all possible triggers otherthan AWS Gateway?

I tested with aws x-ray, it is supporting traces for AWS Gateway and Lambda correlation.

But I was stuck at other possible lambda triggers.

I need to derive correlation for all possible lambda triggers.
trigger(API Gateway or Streams or Events..) --------------> Lambda ---------------> DynamoDB

**Comment by wangzlei** [comment]
API Gateway and SNS as Lambda triggers can generate end to end trace in Xray, the trace looks like trigger --> Lambda --> downstream...
Not all Lambda triggers support end to end traces, there are 2 kinds of case. 
1) the trigger does not integrate with xray, like cloudwatch log. Because lambda function is invoked by a service that is not instrumented, the lambda function will be the first node of a trace.
2) SQS, even SQS has integrated xray but a Lambda function will poll a batch of SQS events, every SQS event might have a xray trace id respectively. In this case Lambda function cannot propagate trace header so has to start a new trace. see details in [thread](https://github.com/aws/aws-xray-sdk-node/issues/208)
