### ISSUE TITLE
Lambda is not traced when a Lambda@Edge make the invocation

### ISSUE THREAD

**Issue by yvele** [aws/aws-xray-sdk-node#348]
I have a Lambda@Edge and I know that [X-Ray is not supported on Lambda@Edge](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html#lambda-requirements-lambda-function-configuration).

I also have a "classic" Lambda function (in eu-west-1) that have active X-Ray tracing enabled.

When my Lambda@Edge function invoke my "classic" Lambda function, the "classic" Lambda function get not traced in X-Ray.

Is that behaviour normal? Is this documented? Are there workaround?

See also https://stackoverflow.com/questions/59386791/aws-x-ray-not-working-in-edge-lambda-and-authorizer-lambda

**Comment by wangzlei** [comment]
Hi, 

Thanks for diving Xray in Lambda. By printing the environment variables of your Lambda@Edge you may see the `_X_AMZN_TRACE_ID` is always end with `sampled=0`, because Lambda@Edge does not support XRay tracing enabled. You can also see `sampled=0` in a non-Edge Lambda function if not tracing enabled. In Lambda design, it actually use XRay trace id `sample=0` to disable XRay.

This trace id would be propagated to downstream service, which is a "classic" Lambda function in your case, and keeps `sampled=0`. That causes even enable tracing in downstream, the Xray SDK in downstream can not export trace to Xray. I believe no only Lambda, any direct downstream AWS Service would not have traces after Lambda@Edge. This problem is still caused by Lambda@Edge does not support XRay.

Before Lambda@Edge supports Xray, a workaround I can imagine is to add a special middle service between your Lambda@Edge and downstream service(like a classic Lambda function), do not call downstream service directly. This middle service must not support XRay propagation so it can stop the trace id `sampled=0` be propagated to downstream. Based on XRay design, if a service does not get trace id from upstream, it will generate a new trace id.

FYI: [AWS Lambda environment variables](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html), [XRay trace header](https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader)

**Comment by willarmiros** [comment]
@yvele I'm going to close out this issue, please comment if you still have questions.

**Comment by yvele** [comment]
> add a special middle service

What kind of middle service? 

Is there no way to tell Lambda@Edge NOT to add a `_X_AMZN_TRACE_ID` at all?

**Comment by yvele** [comment]
Ok I found a workaround by deleting `_X_AMZN_TRACE_ID` in my Lambda@Edge just before calling my downstream Lambda:

```js
const traceId = process.env._X_AMZN_TRACE_ID;
delete process.env._X_AMZN_TRACE_ID;

let response;
try {
  response = await this.lambda.invoke(params).promise();
} finally {
  process.env._X_AMZN_TRACE_ID = traceId;
}
```
