### ISSUE TITLE
SES - SendRawEmail - InvalidParameterValue: Missing required header 'To'.

### ISSUE THREAD

**Issue by jweyrich** [aws/aws-xray-sdk-node#354]
Looks like `SendRawEmail` is throwing an exception in the captured SES client.

![image](https://user-images.githubusercontent.com/206930/97443250-97f8d800-1909-11eb-9337-9ed09027dd87.png)

Here's the relevant part of my Lambda execution timeline:

![image](https://user-images.githubusercontent.com/206930/97443542-e908cc00-1909-11eb-8e78-4a1c4adef2f8.png)

**Comment by willarmiros** [comment]
Hi @jweyrich,

Can you share which version of this SDK you're using and the code you're using to instrument your client? Also, do you believe this issue is being caused by the X-Ray SDK, or is it just being reported by the SDK's interception of your SES client? I think there might be an issue with the way you're making the request to SES, which is causing the *AWS SDK* to throw an error, but the error's stack stack trace just happens to include the X-Ray SDK because it's generated [here](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/patchers/aws_p.js#L77) and recorded [here](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/patchers/aws_p.js#L106).

**Comment by jweyrich** [comment]
Hi @willarmiros. We're using @types/aws-sdk 2.7.0 and deploying to AWS Lambda using the Node.js 10.x runtime. It should provide aws-sdk 2.712.0 according to [the docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). 

> I think there might be an issue with the way you're making the request to SES, which is causing the AWS SDK to throw an error,

I'll investigate it further. From what I saw in our codebase, there's a validator that shouldn't accept an empty/null/undefined value for the destination property. But the codebase is somewhat involved - there are some layers and a 3rd party that does the SES call on our behalf. I'll close this case for now since I cannot confirm this right away. Thank you for the reply!
