### ISSUE TITLE
Error Subsegment too large 

### ISSUE THREAD

**Issue by nmaves** [aws/aws-xray-sdk-node#384]
We are getting the below error and we are having issues tracking it down.  We could not find anywhere in the docs where it states that there is a max size on a Subsegment.

If we set our threshold to 5 we see this error.  If I set it to 0 (zero) I don't see the error.  Is there any issue setting that threshold to 0?  Is there an easy way to find the offending subsegment?

 Subsegment too large to send: {"trace_id:"1-603a65fa-a0aded86fd2beaaca72ab290","id":"96b96c57c4273ecb"} (20156 bytes).

**Comment by wangzlei** [comment]
Hi,

XRay Segment documents can be up to 64 kB in size. The Error code `EMSGSIZE` means the UDP diagram is over MTU, that is the network config in your local. Please run command `sysctl -a|grep gram` to see if it is lower than 20156 bytes.
Xray sdk does not cache and batch segment if Threshold set to 0, that will increase the number of UDP diagram from your App to xray daemon. But since Xray Daemon will batch these segments before sending to AWS XRay backend, threshold 0 in XRay SDK is acceptable.
Currently we have no efficient way to detect the large segment, turn on log debug can print all of segments, but have to manually find the large one.

**Comment by nmaves** [comment]
Thanks!
