### ISSUE TITLE
Can't get captureAsyncFunc and addAnnotation working in Node.js Lambda + HTTP API

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-xray-sdk-node#418]
I've read the docs, and am having trouble understanding how to do manual tracing in my Lambda function (behind an HTTP API route).

I'm doing the following:

```js
import AWSXRay from 'aws-xray-sdk';

AWSXRay.enableManualMode();

export const handler = event => {
  AWSXRay.getSegment().addAnnotation('testkey', 'value');

  await AWSXray.captureAsyncFunc('mytest', async () => {
    // async code
  });

  return { data: 'stuff' };
};
```

First, `AWSXRay.getSegment()` returns `undefined`, which I thought was strange. I thought Lambda automatically has a default segment created. How do we access it?

Also, I see nothing about 'mytest' in the traces in the AWS Console.

What am I getting wrong?

**Comment by TonyLB** [comment]
Well, just for starters, you're not passing a subsegment argument to your async func call, which means you can't manually call "subsegment.close()", which means (I think) that your subsegment never gets completed and logged ... though I'm pretty fuzzy on XRay, so I could be misunderstanding that completely.

But when I do something like this, it does generate a subsegment:

`await AWSXRay.captureAsyncFunc('mytest', async(subsegment) => {
  // async code
  subsegment.close()
})`

What doesn't work for me (like ... at all) is trying to use `AWSXRay.captureAWSv3Client(new DynamoDBClient(params), subsegment)' within Lambda.  Similar to what you're seeing, I get no result logged in the traces.  I wonder if we're encountering the same issue from different angles?  Maybe there's something I need to do in order to properly close the subsegments created by the captured AWS-client calls.

**Comment by willarmiros** [comment]
Hi @ffxsam,
You are correct that with Active tracing enabled, the Lambda service automatically generates a segment you can see in X-Ray. However because the Lambda service manages that segment, it is completely immutable by the function handler code. See the "Important" note in the [X-Ray Lambda integration docs](https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html). Instead, you should be able to create a subsegment (as @TonyLB suggested) and attach that annotation to the subsegment, rather than to the top-level immutable segment as you're trying to today.

@TonyLB the `captureAWSv3Client` API is temporarily rolled back as a no-op in v3.3.1 due to errors experienced by some users. We're actively working on fixing those and re-releasing it soon, see #411 for updates.
