### ISSUE TITLE
captureAWSv3Client doesn't work with ECMAScript Modules

### ISSUE THREAD

**Issue by BorntraegerMarc** [aws/aws-xray-sdk-node#491]
The following package.json:
```
{
  "type": "module",
  "main": "index.js",
  "dependencies": {
    "@aws-sdk/client-dynamodb": "^3.46.0",
    "aws-xray-sdk-core": "^3.3.4",
  }
}
```

With the following code:
```js
import { DynamoDB } from "@aws-sdk/client-dynamodb";
import * as AWSXRay from "aws-xray-sdk-core";

const client = AWSXRay.captureAWSv3Client(new DynamoDB({ region: "eu-central-1" }));
```

Produces the error:
```
const client = AWSXRay.captureAWSv3Client(new DynamoDB({ region: "eu-central-1" }));
                       ^

TypeError: AWSXRay.captureAWSv3Client is not a function
    at file:///lambda-createPatient/index.js:5:24
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by NathanielRN** [comment]
Hi @BorntraegerMarc !

Thanks for bringing up this issue and providing very useful reproduction code. 🙂

### Solution

It seems like your program will work if you just change it to import the AWS X-Ray SDK like this:

```js
import AWSXRay from "aws-xray-sdk-core";
```

But any name besides `AWSXRay` works here.

### Explanation

`import foo from "aws-xray-sdk-core"` works because we are importing the package's default export (this is why the name we use does not matter).

However, when you do `import * as foo from "aws-xray-sdk-core"` you tell JS that you _seriously_ want everything as it is raw. That means that instead of getting the default export:

```json
{
    "function1": {},
    "function2": {}
}
```

You get this:

```json
{
    "default": {
        "function1": {},
        "function2": {}
    }
}
```

So you could have also done `AWSXRay.default.captureAWSv3Client` but that's probably not as clean. 🙂 

[This StackOverflow post](https://stackoverflow.com/questions/55285737/import-as-react-from-react-vs-import-react-from-react) suggests that we could make both work, but also suggests it would be a hacky workaround that probably should not work 😓

**Comment by BorntraegerMarc** [comment]
Gotcha, thx!

**Comment by hannesj** [comment]
It seems there is a mismatch between the Typescript types and the actual exports. According to the `*.d.ts`-files the functions are exported as named exports, not a default export, while in reality, they are exported using CJS syntax, which only generates a default export.
