### ISSUE TITLE
The dependency cls-hooked used in "aws-xray-sdk-core" is very old version which is a security concern

### ISSUE THREAD

**Issue by gvrao254** [aws/aws-xray-sdk-node#509]
Hi
We're using "aws-xray-sdk-core" package in our lambda's. But it has a dependency on **cls-hooked** which again has a dependency on **async-hook-jl** which has a dependency on Minimist. **async-hook-jl & cls-hooked are published 5 years ago** & async-hook-jl is using 0.0.8 version of Minimist where as it's latest version is 1.2.6.

Minimist lower version is not directly in aws-xray-sdk but in **async-hook-jl which is used by aws-xray-sdk.**
async-hook-jl has minimist 0.0.8 in it's yarn.lock file

**I raised the issue before but was suggested to install 3.3.5 version but even after I upgrade to SDK (v3.3.5) using package-lock.json. When install the node modules, in async-hook-jl I'm still getting Minimist 0.0.8**

Minimist version < 1.2.6 is vulnerable to https://github.com/advisories/GHSA-xvch-5gv4-984h

Can you please find a way to remove dependency on cls-hooked or upgrade them so that Minimist is upgraded to latest version. This is blocking our deployments as my org's security team is flagging the version of Minimist

**Comment by willarmiros** [comment]
Hi @gvrao254,

Thanks for raising this. I understand how the dependency is being pulled in now. Unfortunately we depend on `async-hook-jl` through `cls-hooked`, which is a fundamental dependency of the SDK. The only way to remove the dependency is to switch to `AsyncLocalStorage` as described in #338. 

That being said, due to resource issues from our end, I cannot provide an ETA for making this change. If anyone from the community can contribute a PR, it would be welcome. Alternatively, the [AWS Distro for OpenTelemetry](https://aws-otel.github.io/docs/getting-started/js-sdk/trace-manual-instr) offers first-class X-Ray support and is actively maintained.

**Comment by willarmiros** [comment]
Furthermore, can you confirm that minimist 0.0.8 is actually being downloaded, or is it just the `yarn.lock` file that is being downloaded? #492 and #507 confirmed they were false positives

**Comment by gvrao254** [comment]
It's just in yarn.lock not being downloaded.

**Comment by srprash** [comment]
Closing the issue since this is a false positive and the actual vulnerable dependency is not being downloaded.

**Comment by carolabadeer** [comment]
As @srprash mentioned, confirmed that minimist 0.0.8 originates from the [async-hook-jl yarn.lock](https://github.com/Jeff-Lewis/async-hook-jl/blob/88630f0f507b848ba3d4e3d5ba8f46a05aad8879/yarn.lock#L600-L602) and is not directly downloaded by the X-Ray Node SDK.
