### ISSUE TITLE
End of support for X-Ray SDK? 

### ISSUE THREAD

**Issue by marekq** [aws/aws-xray-sdk-node#515]
Hey folks,

I noticed the readme of this repo got updated with a recommendation not to use the SDK anymore in favour of Otel. 

![Screenshot 2022-07-01 at 13 07 36](https://user-images.githubusercontent.com/682391/176883671-57c2f7e3-c1ef-44b7-abad-fefed4874b9f.png)

Is there a cutoff date when this SDK will no longer be supported? I haven't seen any messaging around this yet, but wondering what you can share. We are very actively using the SDK at Stedi, so it would be great to learn more.

**Comment by wangzlei** [comment]
Hi, the exact plan has not been decided yet. Once we have we will share with users in public.

The deprecation process would take a year. The recommendation for new users is onboard OTel instead of XRay sdk because OTel supports more new feature. XRay would stop new feature support but still provide maintenance support like bug fix for a long time to keep the interests of existing user.

**Comment by marekq** [comment]
Thanks for the clear answer, much appreciated @wangzlei !
