### ISSUE TITLE
[ aws-xray-sdk-fastify] Typo of FastityLoggerInstance AND aws-sdk dependency absent

### ISSUE THREAD

**Issue by vaibhavgupta-bst** [aws/aws-xray-sdk-node#587]
After installing aws-xray-sdk-fastify^3.5.0 and using it as plugin, I got a few errors and below are my queries for the same
1. There's no attribute Fasti**t**yLoggerInstance in fastify instead it should have been Fasti**f**yLoggerInstance [ aws-xray-sdk-fastify/lib/plugin.d.ts ]?
![image](https://user-images.githubusercontent.com/51628840/234460276-aeda8a50-0ce9-4d7f-a001-20e0a2d7b271.png)

2. aws-sdk dependency is not present [ aws-xray-sdk-fastify/lib/private/configure-aws-x-ray-sync.js ]
![image](https://user-images.githubusercontent.com/51628840/234460693-6ff88b65-e6e5-4b83-8e64-9b267cad5787.png)

**Comment by carolabadeer** [comment]
Hi @vaibhavgupta-bst, thank you for creating this issue and bringing this to our attention! I have created a PR (#589) to fix the typo you pointed out in `FastifyLoggerInstance`. 

Regarding the second issue you mentioned, we take a [direct dependency on the aws-sdk package in the root package.json](https://github.com/aws/aws-xray-sdk-node/blob/master/package.json#L20), but not in the sub-packages contained within this SDK. Since the direct dependency is in the root package.json, all packages contained within this monorepo will pull their dependencies from there and add on the dependencies in their respective package.json. You'll notice that's also the case for the aws-xray-sdk-core package, which contains all the AWS SDK and HTTP instrumentation logic (`AWSXRay.captureAWS` function).
