### ISSUE TITLE
aws-xray-sdk-core increased size due to aws-sdk

### ISSUE THREAD

**Issue by jostendorf** [aws/aws-xray-sdk-node#80]
Recently a change was completed to move aws-sdk out of dependencies into dev dependencies in the parent package.json.  Is it possible to move it in the aws-xray-sdk-core package.json as well?  Or will that cause issues?

**Comment by chrisradek** [comment]
Hi @jostendorf 
The aws-xray-sdk-core package does require the aws-sdk to be present at runtime for the centralized sampling functionality to work, so we can't move it to be a dev dependency.

Are you generating a bundle for your app? #73 will address some of the size concerns by only importing the xray service instead of the entire SDK, though if you're pushing all of node_modules somewhere then you'll still see the entire SDK on disk.

**Comment by jostendorf** [comment]
You don't need to put the aws-sdk in a lambda layer.  You get it for free in the lambda container.  I have figured out a way to remove this nested dependency using serverless-webpack.  This issue can be closed.  

Add this to the custom tag:

    packagerOptions:
      scripts:
        - rm -rf node_modules/aws-sdk
