### ISSUE TITLE
Need Sample Node.js code on how to use AWS-SDK with node function in *.js files

### ISSUE THREAD

**Issue by nagendradarla** [aws/aws-xray-sdk-node#85]
I have below questions specific to out project.
- Can we use AWS-SDK with out node.js files and function on AWS with minimal changes. Right now the documentation is at very high level. I do not understand where the code changes have to be done.
- Do we have to make changes in each and every function in *.js files OR one code change per *.js file OR one code change across all *.js files.

**Comment by chrisradek** [comment]
@nagendradarla 
Are you looking for an example of how to instrument your code that is using the AWS SDK?

Are you also using a framework like express to process incoming requests, or do you want an example that's just an app using the AWS SDK?

**Comment by chrisradek** [comment]
@nagendradarla 
Here's a simple example of how to use xray with the AWS SDK.

```javascript
// wrapper.js - helper function to create initial segment
const xray = require('aws-xray-sdk');

function traceWrapper(task) {
    const namespace = xray.getNamespace();
    const rootSegment = new xray.Segment('Root');

    namespace.run(() => {
        xray.setSegment(rootSegment);

        task();
    });

    process.once('beforeExit', () => {
        rootSegment.close();
    });
}

module.exports = {
    traceWrapper: traceWrapper
};
```

```javascript
// index.js - The main script to run
const {traceWrapper} = require('./wrapper');
const AWS = require('aws-sdk');
const xray = require('aws-xray-sdk');
xray.captureAWS(AWS);

xray.setLogger(console);

traceWrapper(function() {
  const s3 = new AWS.S3({region: 'us-east-1'});

  s3.listBuckets((err, data) => {
    if (err) {
      console.error(err);
    } else {
      console.log(data);
    }
  });
});
```

Assuming you have these files and the [AWS XRay daemon](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-local.html) runing, `node index.js` should print your S3 buckets and send trace data to XRay.

XRay requires a root `Segment` to signify the start of a `trace`. The `traceWrapper` function in my example creates the segment and that segment is used until the process exits.

Typically when using a framework like `express`, you'll want a trace to represent the actions that occur from the point that you receive a request from a client, to the point you send the response back, so you'll have a separate 'root' segment for each request you process. The XRay SDK has some helpers to make this easier, for example with [express](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/express#automatic-mode-examples).

It looks like you might be using hapi and getting this error. If my above example doesn't help you resolve that, can you share a sample so I can reproduce your issue?

**Comment by nagendradarla** [comment]
Thanks @chrisradek 
- I will try your sample code
- So it means that we have to write a wrapper and use it around each lambda function? Please confirm
- Is there any simpler way to configure or code at once place so that all the lambda functions will be monitored?

**Comment by chrisradek** [comment]
@nagendradarla 
When you're running inside a Lambda function and have [xray enabled](https://docs.aws.amazon.com/lambda/latest/dg/enabling-x-ray.html), then the xray sdk will automatically create the 'root' segment for you. Lambda provides the data the Xray SDK needs to be able to construct this. You don't need to write a wrapper in this case.

Have you already given that a try? I would recommend first testing your Lambda function using callbacks (instead of promises/ async await) to verify that tracing is working.

**Comment by nagendradarla** [comment]
Hi @chrisradek
Can you let me know how to use XRay-Sdk  with promises and async calls.
We have only promises and async functions in my current project.

**Comment by chrisradek** [comment]
@nagendradarla 
Sorry for the delayed response.

If you're using `async` functions, then you'll want to depend on the `@experimental` version of the xray sdk. When you npm install the xray-sdk, just append `@experimental` to it. Internally, it depends on cls-hooks (instead of continuation-local-storage) which supports async/await.

You can use the stable version of the xray-sdk with promises (just not async/await) if you call [AWSXRay.capturePromise()](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/core#capture-subsegmenets-within-chained-native-promise-using-automatic-mode) to patch the global Promise object after importing the xray SDK.

**Comment by chaitanya11** [comment]
Is there a wait to await or have callback in segment/subsegment close function?

**Comment by chanchiem** [comment]
Can you give us an example snippet of this? It would help us further investigate.
