### ISSUE TITLE
[mysql] Support for getConnection of a pool

### ISSUE THREAD

**Issue by otbe** [aws/aws-xray-sdk-node#87]
Hi there,

I wonder why I dont see any mysql data in my xray traces and therefore I read over the source code of the `captureMysql`function. If I get it right it only patches `execute` and `query` on the return objects of `createConnection` and `createPool`. 
I use [typeorm](https://github.com/typeorm/typeorm) as my ORM tool and it uses under the hood [`getConnection`](https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlDriver.ts#L627) of a pool. 

Any chances to get support for this? Maybe I can help?

Thanks!

BTW: I had to switch to `2.1.0-experimental.1` to get xray working at all. Maybe its related to `cls-hooked` which I use on my own.

**Comment by bradleyharrisonboat** [comment]
@otbe I am in the exact same position as you are with the typeORM getConnection. Have you had any luck?  This is important enough that I may fork but I loathe doing that if it cannot be added back into the main stack

**Comment by chrisradek** [comment]
@otbe 
Thank you for the request. We can take a look at supporting `getConnection`, and would love any help in supporting it, even if that just means providing a simple test case we can verify against.

Side note: Are you using async/await in your code? The experimental tag of the SDK does use cls-hooked instead of continuation-local-storage, with one benefit being it supports async/await.

**Comment by otbe** [comment]
@chrisradek I use async/await in my code but TS transpiles it down to generators because some issues with another lib. If I use the latest version of this lib I get a strange error from [this](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/context_utils.js#L61) line. It seems that `getNamespace` returns null/undefined in my situation :/
